apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uat-staging-cert
  namespace: staging
spec:
  secretName: uat-staging-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "uat.euno-staging.reactiflux.com"
